version: '3.8'

services:
  app:
    build: .
    image: yt_fc:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Mount your local directory to the container
    restart: unless-stopped
